v4: local ij functions to v4 cython
uber/h3-py pull request #240
Opened 2022-05-21 01:28 UTC by isaacbrodsky

2022-05-23 14:53 UTC, kylebarron approved these changes

2022-05-24 00:46 UTC, ajfriend requested changes

2022-05-24 00:46 UTC, ajfriend commented on src/h3/api/_api_template.py
> +        i, j = _cy.cell_to_local_ij(origin, h)
Same here. I'd like to make no changes to this file at this stage.

We will change all these function names (and the broader API as well), just not at this stage of the migration.

2022-05-24 01:26 UTC, ajfriend commented
Also note that we're probably going to rework the Cython API (e.g., #236), so these functions will get significant changes later on anyway. So I'd rather defer the discussion of changes around these functions to the next stage.

2022-05-25 03:30 UTC, ajfriend commented
@isaacbrodsky, so I think I got you to entertain my admittedly idiosyncratic request to remove the Cython function name changes in

- `src/h3/_cy/cells.pxd`
- `src/h3/_cy/cells.pyx`

and the Python function name changes in

- `src/h3/_cy/__init__.py`
- `src/h3/api/_api_template.py`

2022-05-26 00:09 UTC, ajfriend approved these changes
lgtm! thanks!

2022-05-26 00:09 UTC, merged